on: [push]

name: Build

jobs:
  build_and_test_linux:
    name: CaterpillarsLinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dev dependencies
        run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev g++ pkg-config libx11-dev libasound2-dev libudev-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: |
            target/release/caterpillars
  build_and_test_windows:
    name: CaterpillarsWindows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: |
            target/release/caterpillars.exe